# Generated by Django 5.2.7 on 2025-11-17 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='description',
            new_name='bio',
        ),
        migrations.AlterField(
            model_name='blogger',
            name='socials',
            field=models.JSONField(default=dict, help_text="Посилання на соц. мережі, напр.: {'youtube': 'url'}"),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('content', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='bloggers_si_publish_c0cce4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AR', 'Стаття'), ('PT', 'Пост')], default='AR', max_length=2)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(help_text='Напишіть тут повний текст статті або посту', max_length=500)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата публікації контенту')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pieces', to='bloggers_site.blogger')),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='bloggers_si_publish_e4a74c_idx')],
            },
        ),
    ]
